# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrsearchimage',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='flickrsearchimage',
            name='is_discarded',
        ),
        migrations.RemoveField(
            model_name='flickrsearchimage',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='flickrimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flickrimage',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flickrimage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
