# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='exclude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
