# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0002_auto_20170623_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
