# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0002_auto_20170619_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrimage',
            name='license',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flickrimage',
            name='tags',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flickrimage',
            name='thumbnail',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
