# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0002_auto_20170622_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrsearch',
            name='licenses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'All Rights Reserved'), ('1', 'Attribution-NonCommercial-ShareAlike'), ('2', 'Attribution-NonCommercial'), ('3', 'Attribution-NonCommercial-NoDerivs'), ('4', 'Attribution'), ('5', 'Attribution-ShareAlike'), ('6', 'Attribution-NoDerivs'), ('7', 'No known copyright restrictions'), ('8', 'United States Government Work')], default=0, max_length=17),
            preserve_default=False,
        ),
    ]
