# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0002_auto_20170620_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrimage',
            name='thumbnail',
        ),
    ]
