# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0003_flickrsearch_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrsearchimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='flickrsearchimage',
            name='search',
        ),
        migrations.DeleteModel(
            name='FlickrSearchImage',
        ),
    ]
