# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0003_auto_20170619_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrimage',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
