# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0003_auto_20170630_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='tags',
            field=models.TextField(),
        ),
    ]
