# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0004_auto_20170630_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrimage',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Discarded'), (1, 'Approved'), (2, 'Processed'), (3, 'Indeterminate')], null=True),
        ),
        migrations.AlterField(
            model_name='flickrsearch',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
