# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0004_auto_20170619_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrimage',
            name='flickr_image_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
