# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:47
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0005_auto_20170622_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='tags'),
        ),
    ]
