# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0005_auto_20170630_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='tags',
            field=models.TextField(unique=True),
        ),
    ]
