# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0006_auto_20170630_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='tags',
            field=models.TextField(),
        ),
    ]
