# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0007_auto_20170622_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrimage',
            name='license',
            field=models.CharField(blank=True, choices=[('0', 'All Rights Reserved'), ('1', 'Attribution-NonCommercial-ShareAlike'), ('2', 'Attribution-NonCommercial'), ('3', 'Attribution-NonCommercial-NoDerivs'), ('4', 'Attribution'), ('5', 'Attribution-ShareAlike'), ('6', 'Attribution-NoDerivs'), ('7', 'No known copyright restrictions'), ('8', 'United States Government Work')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='flickrsearch',
            name='licenses',
            field=models.CharField(choices=[('0', 'All Rights Reserved'), ('1', 'Attribution-NonCommercial-ShareAlike'), ('2', 'Attribution-NonCommercial'), ('3', 'Attribution-NonCommercial-NoDerivs'), ('4', 'Attribution'), ('5', 'Attribution-ShareAlike'), ('6', 'Attribution-NoDerivs'), ('7', 'No known copyright restrictions'), ('8', 'United States Government Work')], max_length=20),
        ),
    ]
