# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0008_auto_20170630_1106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flickrsearch',
            unique_together=set([('tags', 'tag_mode')]),
        ),
    ]
