# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0009_auto_20170630_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flickrimage',
            old_name='flickr_id',
            new_name='id',
        ),
    ]
