# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0009_auto_20170622_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrsearch',
            name='images',
        ),
        migrations.AddField(
            model_name='flickrsearch',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='search', to='flickr_search.FlickrImage'),
        ),
    ]
