# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0010_auto_20170622_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flickrsearch',
            old_name='photo',
            new_name='images',
        ),
    ]
