# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_search', '0011_auto_20170622_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrimage',
            name='flickr_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flickrimage',
            name='flickr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
