# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0003_auto_20170717_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='annotated_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='annotated_image',
        ),
    ]
