# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('state', models.IntegerField(blank=True, choices=[(0, 'Indeterminate'), (1, 'Discarded'), (2, 'Approved'), (3, 'Processed')], null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='flickr_images')),
                ('owner', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('server', models.CharField(max_length=255)),
                ('farm', models.IntegerField()),
                ('license', models.CharField(blank=True, choices=[('0', 'All Rights Reserved'), ('1', 'Attribution-NonCommercial-ShareAlike'), ('2', 'Attribution-NonCommercial'), ('3', 'Attribution-NonCommercial-NoDerivs'), ('4', 'Attribution'), ('5', 'Attribution-ShareAlike'), ('6', 'Attribution-NoDerivs'), ('7', 'No known copyright restrictions'), ('8', 'United States Government Work')], max_length=2, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('ispublic', models.NullBooleanField()),
                ('isfriend', models.NullBooleanField()),
                ('isfamily', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['state', '-created_at', '-updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='tags')),
                ('tag_mode', models.CharField(choices=[('all', 'AND'), ('any', 'OR')], default=('all', 'AND'), max_length=3)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licenses', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'All Rights Reserved'), ('1', 'Attribution-NonCommercial-ShareAlike'), ('2', 'Attribution-NonCommercial'), ('3', 'Attribution-NonCommercial-NoDerivs'), ('4', 'Attribution'), ('5', 'Attribution-ShareAlike'), ('6', 'Attribution-NoDerivs'), ('7', 'No known copyright restrictions'), ('8', 'United States Government Work')], max_length=20)),
                ('images', models.ManyToManyField(blank=True, related_name='search', to='flickr.Image')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
    ]
