# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': 'updated_at', 'ordering': ['-state', '-created_at', '-updated_at'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='image',
            name='annotation',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='annotations'),
        ),
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Indeterminate'), (1, 'Discarded'), (2, 'Approved'), (3, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='tag_mode',
            field=models.CharField(choices=[('all', 'all'), ('any', 'any')], default=('all', 'all'), max_length=3),
        ),
    ]
