# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0004_auto_20170717_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='skin_pixels_image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='skin_pixel_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.Image'),
        ),
    ]
