# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import media_field.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', media_field.db.MediaField(blank=True, max_length=255, null=True, upload_to='')),
                ('query', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Search',
                'verbose_name': 'Search',
                'get_latest_by': 'updated_at',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
