# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:38
from __future__ import unicode_literals

from django.db import migrations
import media_field.db


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170613_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='image',
            field=media_field.db.MediaField(blank=True, default=0, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
