# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170613_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrsearch',
            name='name',
        ),
        migrations.AddField(
            model_name='flickrsearch',
            name='url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
