# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170613_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flickrsearch',
            options={'get_latest_by': 'updated_at', 'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Flickr search', 'verbose_name_plural': 'Flickr searches'},
        ),
    ]
