# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170613_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrsearch',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
