# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_flickrsearch_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrsearch',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
