# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_flickrsearch_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrsearch',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
    ]
