# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_flickrsearch_is_discarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrsearch',
            name='url',
        ),
    ]
