# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_flickrsearch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrsearch',
            name='flickr_image_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
