# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_flickrsearch_flickr_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrsearch',
            name='flickr_image_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
