# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170613_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrsearch',
            name='flickr_image_id',
            field=models.CharField(max_length=255),
        ),
    ]
